name = "backend"
compatibility_date = "2023-12-01"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiMzc3OWU3NDctMjg5My00NDJiLTk4YjctMjljMGQyNmU4ZGUwIiwidGVuYW50X2lkIjoiZmFjNDc2MzMwNWNiZGM1MjFlNzE2NjE1ODRhM2QxODY3MGUwNzAwNDA2MmQzN2NiZmE2ZDUzNDNjMGMyMTA5ZSIsImludGVybmFsX3NlY3JldCI6IjUyODc3YWE5LTcyOGEtNDhiZi1hM2ViLWJiNDZkNDViZGVhMiJ9.a7Tpyie9FVheckX4zSkRf1hMRNu4SKMrqm4xy6iGqYg"
JWT_SECRET = "123"
